apiVersion: v1
experiment:
- tag: server
  image: vitorenesduarte/quad-example
  replicas: 3
  env:
  - name: TYPE
    value: server
  workflow:
    end:
      name: client2_end
      value: 6
- tag: client1
  image: vitorenesduarte/quad-example
  replicas: 3
  env:
  - name: TYPE
    value: client
  - name: OPS
    value: 100
  workflow:
    start:
      name: server-ready
      value: 3
- tag: client2
  image: vitorenesduarte/quad-example
  replicas: 6
  env:
  - name: TYPE
    value: client
  - name: OPS
    value: 200
  workflow:
    start:
      name: client1_end
      value: 3
